[workspace]
members = [
    "jupiter-swap-api-client",
    "example",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
solana-sdk = "*"
solana-client = "*"
solana-account-decoder = "*"
