[package]
name = "jupiter-swap-api-client"
version = "0.1.0"
description = "Jupiter Swap API rust client"
edition = { workspace = true }

[dependencies]
serde_json = "*"
anyhow = "*"
serde = { version = "*", features = ["derive"] }
solana-sdk = { workspace = true }
solana-account-decoder = { workspace = true }
base64 = "*"
serde_qs = "*"
reqwest = { version = "*", features = ["json"] }
rust_decimal = "*"

[dev-dependencies]
tokio = { workspace = true }
